### ISSUE TITLE
Error to run Rserve with R 3.5.0 - long vectors not supported yet: qap_encode.c:36

### ISSUE THREAD

**Issue by Bio7** [s-u/Rserve#102]
I just installed R 3.5.0 on two Macs (High Sierra, El Capitan) and tried to install the latest Rserve version:

It compiled succesfully and the server starts. At runtime however I get the following error when I try to connect the client to the Server. The client connection can't be established.

> Error in run.Rserve() : long vectors not supported yet: qap_encode.c:36

https://github.com/s-u/Rserve/blob/master/src/qap_encode.c#L36

I think this has something to do with the long indexing in R?

Here the install command (I use Rserve in cooperative mode locally):

sudo PKG_CPPFLAGS=-DCOOPERATIVE R CMD INSTALL Rserve_1.8-5.tar.gz

Here the current session Info for completeness (but the error also occurs on a High Sierra laptop!):

> sessionInfo()

R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0

**Comment by Bio7** [comment]
I rechered a little bit and found in the R news some pointers for long vectors:

https://cran.r-project.org/src/base/NEWS

A detailed description of the changes can be found in this article:

https://www.sciencedirect.com/science/article/pii/S0098300416307415

So it might be possible that the LENGTH function in line 36:

https://github.com/s-u/Rserve/blob/master/src/qap_encode.c#L36

can be replaced by XLENGTH?

**Comment by hideaki** [comment]
I got the same error, and replacing LENGTH() with XLENGTH() as @Bio7 suggested does seem to eliminate the error.

**Comment by s-u** [comment]
It needs more than just the one occurrence. So I added large vector support to the QAP encoding and decoding. It would be interesting to find out why R create a large vector for something that is actually small - could be a bug in R.

**Comment by yannrichet** [comment]
If it helps:
for me it occurs when calling such very simple call: `connection.parseAndEval("array(0.0,c(4,3))")`
it returns following debug when calling Rserve(debug=T):
`
header read result: 16
DUMP [16]: 03 00 00 00 19 00 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 25 bytes)
parsing parameters (buf=0x55ce86451170, len=25)
DUMP [25]: 04 14 00 00 61 72 72 61 79 28 30 2e 30 2c 63 28 34 2c 33 29 29 0a 00 00 00  |....array(0.0,c(4,3))....
PAR[0]: 00000019 (PAR_LEN=20, PAR_TYPE=4, large=no, c=0x55ce86451170, ptr=0x55ce86451174)
CMD=00000003, pars=1
parseString("array(0.0,c(4,3))
")
buffer parsed, stat=1, parts=2
result type: 20, length: 1
R_tryEval(xp,R_GlobalEnv,&Rerror);
Calling R_tryEval for expression 1 [type=6] ...
Expression 1, error code: 0
expression(s) evaluated (Rerror=0).
[*has attr*] Vector of real variables: 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000
getStorageSize(0x55ce853a3fa8,type=14,len=12) Erreur : les vecteurs longs ne sont pas encore supportés : qap_encode.c:36
Fatal error: unable to initialize the JIT
 `
my R:
`> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base 

`

**Comment by pgrech2** [comment]
Any updates, receiving same issue.

**Comment by Keswiik** [comment]
@pgrech2 you may be pulling an older release of Rserve if you're installing from CRAN (`install.packages('Rserve')`).

I ran into this issue earlier and needed to install via RForge:
`install.packages('Rserve',,"http://rforge.net/",type="source")`

**Comment by MathieuNls** [comment]
Hi,

I have the same issue and, when trying to install it from rforge, I got the following error:

```

**Comment by yannrichet** [comment]
In your last case, it seems that just libssl is missing. Probably not related to current thread.

**Comment by AcaDemIQ** [comment]
Excuse me, but I have this problem on the 1.8.6
```
Ошибка: длинные вектора еще не поддерживаются: qap_encode.c:36
Fatal error: unable to initialize the JIT
```

Which additional information should I send for debug analysis for you?

P.S. Sorry about my English :)

**Comment by s-u** [comment]
Please make sure you have the latest version, this should have been fixed in 484f5fe

**Comment by quaeler** [comment]
I have what appears to be the latest version, 3.5.2, on macOS 10.13.6 and this is still occurring:
```
Rserv started in daemon mode.
Error: long vectors not supported yet: qap_encode.c:36
Fatal error: unable to initialize the JIT

> version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo              
>
```

**Comment by yonibaciu** [comment]
@Keswiik comment on Aug 1st 2018 helped me with the "long vectors not supported yet: qap_encode.c:36" error

**Comment by yonibaciu** [comment]
> @pgrech2 you may be pulling an older release of Rserve if you're installing from CRAN (`install.packages('Rserve')`).
> 
> I ran into this issue earlier and needed to install via RForge:
> `install.packages('Rserve',,"http://rforge.net/",type="source")`

The above worked for me

**Comment by afs091** [comment]
Greetings,

I tried rserve version 1.7.1 installed via sudo apt install cran-r-rserve and 1.8.6 installed within R via install.packages('Rserve',,"http://rforge.net/",type="source") but I am still getting the same error:

Error: long vectors not supported yet: qap_encode.c:36
Fatal error: unable to initialize the JIT

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 19.1

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=pt_PT.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=pt_PT.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=pt_PT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0

**Comment by s-u** [comment]
Your `sessionInfo()` doesn't show Rserve - make sure you have the correct version, the error suggests you don't. Check you library paths fro older version. You'll need at least 1.8-6.

**Comment by afs091** [comment]
Thank you for your advice!

> packageVersion('Rserve')
[1] ‘1.8.6’

R CMD Rserve --version
Rserve v1.7-3 ()

sudo netstat -lanp | grep 'Rserve'
tcp        0      0 127.0.0.1:6311          0.0.0.0:*               LISTEN      6135/Rserve

**kill PID**
kill -9 6135

Then I launch Rserve from R
> Rserve()

And everything goes well

However I don't find a way to remove the 1.7-3 version, even with R CMD REMOVE Rserve I can only target the 1.8.6 version never the 1.7-3

Thank you!

**Comment by s-u** [comment]
You likely installed the old version as `sudo` at some point, but not the new one. Check out this path:
```
file.path(R.home(),"bin","Rserve")
```
and remove it.
You can also run in R:
```
Rserve::Rserve()
```
which will show you the full command to run for the currently installed version.

**Comment by yannrichet** [comment]
In case you absolutely need it, I released a fork of 1.7 with just the
LENGTH/XLENGTH patch. There: https://github.com/yannrichet/Rserve-1.7 ,
with sources and binaries. Tested for R 3.5 & 3.6.

**Comment by pavany666666** [comment]
Thanks guys... I had the same problem and Rserve 1.7.5 fixed it for me R 3.6.1.

Appreciate the help!

**Comment by entmike** [comment]
> @pgrech2 you may be pulling an older release of Rserve if you're installing from CRAN (`install.packages('Rserve')`).
> 
> I ran into this issue earlier and needed to install via RForge:
> `install.packages('Rserve',,"http://rforge.net/",type="source")`

Just FYI this is what worked for me.  Thank you.
